fix: dircolors and gpg

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -201,6 +201,30 @@ if [[ -f "$INSTALL_DIR/opt/symlinks" ]]; then
 	[[ $? ]] && print_success "Symlinked configuration files"
 fi
 
+# Set up custom dircolors/LS_COLORS
+# https://unix.stackexchange.com/a/94306
+# https://github.com/trapd00r/LS_COLORS
+if [[ ! -f "$HOME/.dircolors" ]]; then
+	readonly LS_REPO="LS_COLORS"
+	print_process "Downloading LS_COLORS to /tmp directory"
+	# (-#) shows the progress bar as # sign
+	# (-f) fail silently
+	# (-L) follow the headers
+	# (-o) output to a file
+	curl -#fLo "/tmp/$LS_REPO.tar.gz" "https://$GITHUB_URL/trapd00r/$LS_REPO/tarball/master"
+
+	print_process "Extracting files"
+	tar -zxf "/tmp/$LS_REPO.tar.gz" --strip-components 1
+
+	print_process "Copying files"
+	dircolors -b /tmp/$LS_REPO/LS_COLORS > "$HOME/.dircolors"
+
+	print_process "Removing tarball from /tmp directory"
+	rm -rf "/tmp/$LS_REPO.tar.gz"
+
+	[[ $? ]] && print_success "Installed custom LS_COLORS"
+fi
+
 # Copy `.ssh/config`.
 # This prevents them being committed to the repository.
 if [[ ! -d "$HOME/.ssh" ]]; then
